/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vista.registrarAsistenciasReuniones.isNumeric;

/**
 *
 * @author Kami Osita Bebe
 */
public class informacionPagos extends javax.swing.JFrame {

    public metodos metodos = new metodos();

    /**
     * Creates new form login
     */
    public informacionPagos() {
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información de Pagos");
        setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconoExe.png"));
        return retValue;
    }

    public void vaciarTabla() {
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Estado");
        jTable_verPagos.setModel(modelo);
    }

    public void obtenerPagos(int idSocio) throws SQLException {
        vaciarTabla();
        ArrayList<String> pagos = metodos.obtenerPagos(idSocio);
        if (!pagos.isEmpty()) {
            DefaultTableModel modelo;
            modelo = new DefaultTableModel() {
                public boolean isCellEditable(int filas, int columnas) {
                    return false;
                }
            };
            modelo.addColumn("Fecha");
            modelo.addColumn("Estado");
            jTable_verPagos.setModel(modelo);
            for (int i = 0; i < pagos.size() - 1; i = i + 2) {
                if (pagos.get(i + 1).equals("0")) {
                    modelo.addRow(new Object[]{pagos.get(i), "No pagado"});
                } else if (pagos.get(i + 1).equals("1")) {
                    modelo.addRow(new Object[]{pagos.get(i), "Pagado"});
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nombreReunion1 = new javax.swing.JLabel();
        jTextField_codigoUsuario = new javax.swing.JTextField();
        jButton_buscarUsuario = new javax.swing.JButton();
        jLabel_nombreReunion2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_nombres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_verPagos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(691, 615));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Información de Pagos");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 650, -1));

        jLabel_nombreReunion1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion1.setText("Ingrese el código del usuario a buscar");
        getContentPane().add(jLabel_nombreReunion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 310, 43));

        jTextField_codigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_codigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_codigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 98, 470, 40));

        jButton_buscarUsuario.setBackground(new java.awt.Color(30, 139, 204));
        jButton_buscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jButton_buscarUsuario.setText("Buscar");
        jButton_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 131, 39));

        jLabel_nombreReunion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion2.setText("Nombres:");
        getContentPane().add(jLabel_nombreReunion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 610, 20));

        jTextField_nombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombresActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 520, -1));

        jTable_verPagos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable_verPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha", "Estado"
            }
        ));
        jTable_verPagos.setAutoscrolls(false);
        jTable_verPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable_verPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 610, 310));

        jButton1.setBackground(new java.awt.Color(0, 97, 155));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon (1).png"))); // NOI18N
        jButton1.setText("Imprimir reporte de pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 290, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 650, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_codigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoUsuarioActionPerformed
        if (jTextField_codigoUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el ID del Socio");
        } else {
            if (isNumeric(jTextField_codigoUsuario.getText())) {
                ArrayList socio = new ArrayList();
                try {
                    socio = metodos.verSocioC(Integer.parseInt(jTextField_codigoUsuario.getText()));
                } catch (SQLException ex) {
                    //Logger.getLogger(informacionPagos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");
                } catch (IOException ex) {
                    //Logger.getLogger(informacionPagos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");
                }
                if (!socio.isEmpty()) {
                    jTextField_nombres.setText(socio.get(2).toString());
                    try {
                        obtenerPagos(Integer.parseInt(socio.get(0).toString()));
                    } catch (SQLException ex) {
                        Logger.getLogger(informacionPagos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");

                }

            } else {
                JOptionPane.showMessageDialog(this, "ID inválido");
            }

        }
    }//GEN-LAST:event_jTextField_codigoUsuarioActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuarioActionPerformed

        if (jTextField_codigoUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el ID del Socio");
        } else {
            if (isNumeric(jTextField_codigoUsuario.getText())) {
                ArrayList socio = new ArrayList();
                try {
                    socio = metodos.verSocioC(Integer.parseInt(jTextField_codigoUsuario.getText()));
                } catch (SQLException ex) {
                    //Logger.getLogger(informacionPagos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");
                } catch (IOException ex) {
                    //Logger.getLogger(informacionPagos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");
                }
                if (!socio.isEmpty()) {
                    jTextField_nombres.setText(socio.get(2).toString());
                    try {
                        obtenerPagos(Integer.parseInt(socio.get(0).toString()));
                    } catch (SQLException ex) {
                        Logger.getLogger(informacionPagos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");

                }

            } else {
                JOptionPane.showMessageDialog(this, "ID inválido");
            }

        }

    }//GEN-LAST:event_jButton_buscarUsuarioActionPerformed

    private void jTextField_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cont = 0;
        if (jTextField_codigoUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un usuario");
            cont++;
        }
        if (cont == 0) {
            int id = Integer.parseInt(jTextField_codigoUsuario.getText());
            JFileChooser chooser = new JFileChooser();
            int seleccion = chooser.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File fichero = chooser.getSelectedFile();
                metodos.crearReporteUsuario(id, fichero);
                JOptionPane.showMessageDialog(this, "Reporte Generado");
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacionPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new informacionPagos().setVisible(true);
        });
    }

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_buscarUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_nombreReunion1;
    private javax.swing.JLabel jLabel_nombreReunion2;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_verPagos;
    private javax.swing.JTextField jTextField_codigoUsuario;
    private javax.swing.JTextField jTextField_nombres;
    // End of variables declaration//GEN-END:variables
}
