/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kami Osita Bebe
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        this.setResizable(false);
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("../img/iconoExe.png")).getImage());
//        this.setExtendedState(MAXIMIZED_BOTH);
        //
        setTitle("Iniciar Sesión");
        setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconoExe.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_contrasena = new javax.swing.JLabel();
        ingresarUsuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_iniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(746, 560));
        setMinimumSize(new java.awt.Dimension(746, 560));
        setPreferredSize(new java.awt.Dimension(439, 290));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wa.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 320, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 540));

        jPanel2.setBackground(new java.awt.Color(0, 45, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Iniciar Sesión");
        jPanel2.add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 34, 263, 62));

        jLabel_usuario.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setText("USUARIO");
        jPanel2.add(jLabel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 158, 93, -1));

        jLabel_contrasena.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_contrasena.setText("CONTRASEÑA");
        jPanel2.add(jLabel_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 278, -1, -1));

        ingresarUsuario.setBackground(new java.awt.Color(0, 45, 62));
        ingresarUsuario.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        ingresarUsuario.setForeground(new java.awt.Color(109, 210, 255));
        ingresarUsuario.setBorder(null);
        ingresarUsuario.setCaretColor(new java.awt.Color(109, 210, 255));
        ingresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(ingresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 188, 244, 38));

        password.setBackground(new java.awt.Color(0, 45, 62));
        password.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(109, 210, 255));
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(109, 210, 255));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 308, 245, 37));

        jSeparator1.setBackground(new java.awt.Color(109, 210, 255));
        jSeparator1.setForeground(new java.awt.Color(109, 210, 255));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 232, 291, 10));

        jSeparator2.setBackground(new java.awt.Color(109, 210, 255));
        jSeparator2.setForeground(new java.awt.Color(109, 210, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 351, 291, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 188, 37, 38));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 313, -1, -1));

        jButton_iniciarSesion.setBackground(new java.awt.Color(60, 180, 233));
        jButton_iniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_iniciarSesion.setText("INGRESAR");
        jButton_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 418, 170, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 0, 470, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarUsuarioActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        String contrasenia= password.getText();
        String usuario = ingresarUsuario.getText();
        metodos m= new metodos();
        int existe = m.comprobarAdministrador(contrasenia,usuario);
        if(existe == 1){
            m.recuperarPreciosBaseDatos();
            principal v = new principal();
            v.setVisible(true);
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(this, "Administrador no Registrado");
        }
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciarSesionActionPerformed
        // TODO add your handling code here:
        String contrasenia= password.getText();
        String usuario = ingresarUsuario.getText();
        metodos m= new metodos();
        int existe = m.comprobarAdministrador(contrasenia,usuario);
        if(existe == 1){
            m.recuperarPreciosBaseDatos();
            principal v = new principal();
            v.setVisible(true);
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(this, "Administrador no Registrado");
        }
    }//GEN-LAST:event_jButton_iniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresarUsuario;
    private javax.swing.JButton jButton_iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_contrasena;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
