/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WilyAndy
 */
public class modificarConsumos extends javax.swing.JFrame {

    metodos metodos = new metodos();

    /**
     * Creates new form modificarConsumos
     */
    public modificarConsumos() {
        initComponents();
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Consumos");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSocioConsumo = new javax.swing.JTable();
        jLabel_fechaReunion = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();
        jDateChooser_selectorFechaTrabajo = new com.toedter.calendar.JDateChooser();
        jButton_cargarDatosConsumo = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(995, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaSocioConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TablaSocioConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Num. Medidor", "Nombre", "Consumo "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaSocioConsumo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 207, 940, 216));

        jLabel_fechaReunion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_fechaReunion.setText("Socios");
        getContentPane().add(jLabel_fechaReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 159, -1, 37));

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("MODIFICAR CONSUMOS");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 28, 893, -1));

        jDateChooser_selectorFechaTrabajo.setDateFormatString("yyyy-MM-dd");
        jDateChooser_selectorFechaTrabajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jDateChooser_selectorFechaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 99, 204, 33));

        jButton_cargarDatosConsumo.setBackground(new java.awt.Color(255, 255, 255));
        jButton_cargarDatosConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_cargarDatosConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cargar.png"))); // NOI18N
        jButton_cargarDatosConsumo.setText("Cargar Datos");
        jButton_cargarDatosConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cargarDatosConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cargarDatosConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 99, -1, -1));

        Modificar.setBackground(new java.awt.Color(255, 255, 255));
        Modificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        Modificar.setText("Modificar Cosumos");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 441, 229, 39));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 143, 935, 10));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 970, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cargarDatosConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cargarDatosConsumoActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if (jDateChooser_selectorFechaTrabajo.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fecha");
            cont++;
        }
        if (cont == 0) {
            cargarDatos();
        }
    }//GEN-LAST:event_jButton_cargarDatosConsumoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if (jDateChooser_selectorFechaTrabajo.getDate() == null) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FECHA");
            cont++;
        }
        if (cont == 0) {
            int año = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.YEAR);
            int mes = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.MARCH);
            int mesActual = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.MARCH) + 1;
            Calendar calendario = Calendar.getInstance();
            calendario.set(año, mes, 1);
            int ultimoDiaMes = calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
            String fecha = (año + "-" + mesActual + "-" + ultimoDiaMes);
            int fila = TablaSocioConsumo.getRowCount();
            int i;
            ArrayList<Object> valores = new ArrayList<>();
            valores.add(fecha);
            for (i = 0; i < fila; i++) {
                if (!TablaSocioConsumo.getValueAt(i, 4).toString().isEmpty()) {
                    if (isNumeric(TablaSocioConsumo.getValueAt(i, 4).toString())) {
                        String codigo = (String) TablaSocioConsumo.getValueAt(i, 0);
                        valores.add(codigo);
                        String consumoAn = (String) TablaSocioConsumo.getValueAt(i, 3);
                        String tipo = TablaSocioConsumo.getValueAt(i, 4).getClass().toString();
                        if (tipo.equals("class java.lang.String")) {
                            String consumoA = (String) TablaSocioConsumo.getValueAt(i, 4);
                            double diferencia = Double.parseDouble(consumoA) - Double.parseDouble(consumoAn);
                            valores.add(diferencia);
                            valores.add(consumoA);
                        } else {
                            double consumoA = (double) TablaSocioConsumo.getValueAt(i, 4);
                            double diferencia = consumoA - Double.parseDouble(consumoAn);
                            String cadena = String.valueOf(consumoA);
                            valores.add(diferencia);
                            valores.add(cadena);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "VALORES INCORRECTOS, PUEDA QUE CONTENGA LETRAS");
                        cont++;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "NO DEBEN QUEDAR CAMPOR VACÍOS");
                    cont++;
                }
            }
            if (cont == 0) {
                try {
                    metodos.modificarConsumo(valores);
                    metodos.modificar_registrarPagos(valores);
                    JOptionPane.showMessageDialog(this, "ÉXITO AL MODIFICAR LOS DATOS");
                } catch (SQLException ex) {
                    Logger.getLogger(registrarConsumo.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR AL MODIFICAR DATOS..!!");
                }
            }
        }
    }//GEN-LAST:event_ModificarActionPerformed
    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Double.parseDouble(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    public void cargarDatos() {
        ArrayList<String> valores = new ArrayList<>();
        ArrayList<String> consumosActuales = new ArrayList<>();
        int anio = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.YEAR);
        int mes = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.MONTH) + 1;
        System.out.println("MEEES" + mes);
        int dia = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.DAY_OF_MONTH);
        System.out.println();
        try {
            valores = metodos.informacionSocioConsumoAnterior(mes, anio);
            consumosActuales = metodos.informacionSocioConsumoActual(mes, anio);
            DefaultTableModel modelo;
            modelo = new DefaultTableModel() {
                public boolean isCellEditable(int filas, int columnas) {
                    if (columnas == 4) {
                        return true;
                    } else {
                        return false;
                    }
                }
            };

            modelo.addColumn("Codigo");
            modelo.addColumn("Num. Medidor");
            modelo.addColumn("Usuario");
            modelo.addColumn("Consumo Anterior");
            modelo.addColumn("Consumo Actual");
            TablaSocioConsumo.setModel(modelo);
            int cont = 0;
            for (int i = 0; i < valores.size() - 1; i = i + 4) {
                modelo.addRow(new Object[]{valores.get(i), valores.get(i + 1), valores.get(i + 2), valores.get(i + 3), consumosActuales.get(cont)});
                cont++;
                // System.out.println(valores.get(i));
            }
            int[] anchos = {40, 40, 200, 40, 40};

            for (int i = 0; i < TablaSocioConsumo.getColumnCount(); i++) {
                TablaSocioConsumo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);

            }
        } catch (SQLException ex) {
            Logger.getLogger(informacionReuniones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarConsumos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JTable TablaSocioConsumo;
    private javax.swing.JButton jButton_cargarDatosConsumo;
    private com.toedter.calendar.JDateChooser jDateChooser_selectorFechaTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_fechaReunion;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
