/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author WilyAndy
 */
public class multas extends javax.swing.JFrame {

    /**
     * Creates new form multas
     */
    public multas() throws SQLException {
        admitirNumeros();
        this.setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarDatos();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconoExe.png"));
        return retValue;
    }
    public static void admitirNumeros(){
        JFormattedTextField noAsistirReunion = new JFormattedTextField (new Double(10));
        JFormattedTextField atrasoReunion = new JFormattedTextField (new Double(10));
        JFormattedTextField noAsistirMinga = new JFormattedTextField (new Double(10));
        JFormattedTextField excesoConsumo = new JFormattedTextField (new Double(10));
        JFormattedTextField excesoMeses = new JFormattedTextField (new Double(10));
        JFormattedTextField metrosCubicos = new JFormattedTextField (new Double(10));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        noAsistirReunion = new javax.swing.JTextField();
        atrasoReunion = new javax.swing.JTextField();
        noAsistirMinga = new javax.swing.JTextField();
        excesoConsumo = new javax.swing.JTextField();
        excesoMeses = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        metrosCubicos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        preciobase = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel5.setText("Multa no Asistir a una Reunion");

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Multa no Asistir a una Reunion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Multa no Asistir a una Minga:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Multa por atraso a una Reunion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Multa por exceso de consumo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Multa por meses no pagados:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButton2.setBackground(new java.awt.Color(203, 23, 12));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 130, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(28, 108, 171));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registro de Precios");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 40));

        noAsistirReunion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        noAsistirReunion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(noAsistirReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 149, -1));

        atrasoReunion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        atrasoReunion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        atrasoReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasoReunionActionPerformed(evt);
            }
        });
        getContentPane().add(atrasoReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 149, -1));

        noAsistirMinga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        noAsistirMinga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(noAsistirMinga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 149, -1));

        excesoConsumo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        excesoConsumo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(excesoConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 149, -1));

        excesoMeses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        excesoMeses.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        excesoMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excesoMesesActionPerformed(evt);
            }
        });
        getContentPane().add(excesoMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 149, -1));

        jButton1.setBackground(new java.awt.Color(0, 97, 155));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 119, 41));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cantidad de metros cubicos base:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        metrosCubicos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        metrosCubicos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        metrosCubicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metrosCubicosActionPerformed(evt);
            }
        });
        getContentPane().add(metrosCubicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 149, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("$");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Precio Base");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        preciobase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        preciobase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        preciobase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciobaseActionPerformed(evt);
            }
        });
        getContentPane().add(preciobase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 149, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 510, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("$");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("$");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("$");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 70, 20, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("$");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("$");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 300));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasoReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasoReunionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasoReunionActionPerformed

    private void excesoMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excesoMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excesoMesesActionPerformed

    public void cargarDatos() throws SQLException{
        metodos m = new metodos();
        ArrayList<Double> valores = new ArrayList<>();
        valores = m.obtenerPreciosM();
        noAsistirReunion.setText(valores.get(0).toString());
        atrasoReunion.setText(valores.get(1).toString());
        noAsistirMinga.setText(valores.get(2).toString());
        excesoConsumo.setText(valores.get(3).toString());
        excesoMeses.setText(valores.get(4).toString());
        metrosCubicos.setText(valores.get(5).toString());
        preciobase.setText(valores.get(6).toString());
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cont=0;
        if(noAsistirReunion.getText().isEmpty()){
            cont++;
        }if(atrasoReunion.getText().isEmpty()){
            cont++;
        }if(noAsistirMinga.getText().isEmpty()){
            cont++;
        }if(excesoConsumo.getText().isEmpty()){
            cont++;
        }if(excesoMeses.getText().isEmpty()){
            cont++;
        }if(metrosCubicos.getText().isEmpty()){
            cont++;
        }if(preciobase.getText().isEmpty()){
            cont++;
        }
        if(cont==0){
            double noAsistiraReunion = Double.parseDouble(noAsistirReunion.getText());
            double atrasoaReunion = Double.parseDouble(atrasoReunion.getText());
            double noAsistiraMinga = Double.parseDouble(noAsistirMinga.getText()); 
            double consumoExceso = Double.parseDouble(excesoConsumo.getText());
            double mesesExceso = Double.parseDouble(excesoMeses.getText());
            double cantidadMetros = Double.parseDouble(metrosCubicos.getText());
            double precioBase = Double.parseDouble(preciobase.getText());
            metodos m = new metodos();
            m.registrarPrecios(noAsistiraReunion,atrasoaReunion,noAsistiraMinga,consumoExceso,mesesExceso,cantidadMetros, precioBase);
            JOptionPane.showMessageDialog(this, "Datos Actualizados");
        }else{
            JOptionPane.showMessageDialog(this, "Debe Llenar todos los campos");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void metrosCubicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metrosCubicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metrosCubicosActionPerformed

    private void preciobaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciobaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciobaseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new multas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(multas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atrasoReunion;
    private javax.swing.JTextField excesoConsumo;
    private javax.swing.JTextField excesoMeses;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField metrosCubicos;
    private javax.swing.JTextField noAsistirMinga;
    private javax.swing.JTextField noAsistirReunion;
    private javax.swing.JTextField preciobase;
    // End of variables declaration//GEN-END:variables
}
