/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import com.itextpdf.text.DocumentException;
import java.awt.ScrollPane;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import static vista.registrarAsistenciasReuniones.isNumeric;

/**
 *
 * @author MaGaby Delgado
 */
public class realizarCobros1 extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    int idSocioConsultas = 0;
    static int cod = 0;
    static double multaxReunion = 0, multaTrabajo = 0;
    static double lecturaA = 0;
    static double lecturaN = 0;
    static double totalSoloConsumo = 0.0;
    static double excesoConsumo = 0.0;
    static double totalConsumo = 0.0;
    static double difConsumo;
    static double meses = 0.0;
    static double total = 0.0;
    static double totalSoloMes = 0.0;
    static double valorMesesqueDebe = 0.0;
    static double mesesQueDebe = 0.0;
    static double Reinstalacion = 0.0;
    ArrayList<String> factura;
    JScrollPane scrollPane;

    
    public realizarCobros1() {
        this.setResizable(false);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Asistencias");
        setLocationRelativeTo(null);
        deshabilitarText();
        scrollPane=new JScrollPane();
    }

    public void deshabilitarText() {
        lecturaActual.setEditable(false);
        lecturaAnterior.setEditable(false);
        multaMinga.setEditable(false);
        multaReunion.setEditable(false);
        recargoExcesoConsumo.setEditable(false);
        ValorMesesDebe.setEditable(false);
        Total.setEditable(false);
        consumoTotal.setEditable(false);
    }

    public void llenarTabla(ArrayList Resultados) {
        modelo = new DefaultTableModel() {
            public boolean isCellEditable(int filas, int columnas) {
                if (columnas == 2) {
                    return true;
                } else {
                    return false;
                }
            }
            //modelo.getColumnModel().getColumn(0).setPreferredWidth(20);
        };

        modelo.addColumn("Nombre");
        modelo.addColumn("Codigo");

        TablaPersonas.setModel(modelo);
        for (int i = 0; i < Resultados.size() - 1; i += 2) {
            modelo.addRow(new Object[]{Resultados.get(i + 1), Resultados.get(i)});
            // System.out.println(valores.get(i));
        }
    }

    public String llenarCeros(int tamanio, String original) {
        String cero = "";
        for (int i = tamanio; i < 6; i++) {
            cero = cero + "0";
        }
        return cero + original;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_nombreReunion = new javax.swing.JLabel();
        jTextField_codigoUsuario = new javax.swing.JTextField();
        jButton_buscarUsuario2 = new javax.swing.JButton();
        jLabe = new javax.swing.JLabel();
        fechaCobro = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPersonas = new javax.swing.JTable();
        jLabel_nombreReunion1 = new javax.swing.JLabel();
        jButton_buscarUsuario = new javax.swing.JButton();
        jLabe2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_nombreReunion2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelMedidor = new javax.swing.JLabel();
        jLabel_nombreReunion3 = new javax.swing.JLabel();
        jLabel_nombreReunion4 = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        jLabel_nombreReunion6 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        jLabe1 = new javax.swing.JLabel();
        jLabe8 = new javax.swing.JLabel();
        multaMinga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        multaReunion = new javax.swing.JTextField();
        jLabe9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lecturaActual = new javax.swing.JTextField();
        jLabe11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lecturaAnterior = new javax.swing.JTextField();
        jLabe13 = new javax.swing.JLabel();
        diferencia = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabe16 = new javax.swing.JLabel();
        consumoTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabe14 = new javax.swing.JLabel();
        recargoExcesoConsumo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabe18 = new javax.swing.JLabel();
        jLabe19 = new javax.swing.JLabel();
        mesesquedebe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ValorMesesDebe = new javax.swing.JTextField();
        jLabe15 = new javax.swing.JLabel();
        recargoMeses = new javax.swing.JTextField();
        jLabe10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextReinstalacion = new javax.swing.JTextField();
        jLabe17 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabe7 = new javax.swing.JLabel();
        jButton_imprimir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1010, 868));
        setResizable(false);

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1010, 868));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1010, 868));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1010, 868));

        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 868));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 868));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 868));

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Realizar Cobro");

        jLabel_nombreReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion.setText("Ingrese el nombre o código del socio");

        jTextField_codigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_codigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoUsuarioActionPerformed(evt);
            }
        });

        jButton_buscarUsuario2.setBackground(new java.awt.Color(30, 139, 204));
        jButton_buscarUsuario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jButton_buscarUsuario2.setText("Buscar");
        jButton_buscarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuario2ActionPerformed(evt);
            }
        });

        jLabe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe.setText("Seleccione fecha de pago");

        fechaCobro.setDateFormatString("yyyy-MM-dd");
        fechaCobro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TablaPersonas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPersonas.setFocusable(false);
        jScrollPane2.setViewportView(TablaPersonas);

        jLabel_nombreReunion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_nombreReunion1.setText("Seleccione el usuario que desea*.");

        jButton_buscarUsuario.setBackground(new java.awt.Color(0, 97, 155));
        jButton_buscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick.png"))); // NOI18N
        jButton_buscarUsuario.setText("Aceptar");
        jButton_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuarioActionPerformed(evt);
            }
        });

        jLabe2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabe2.setForeground(new java.awt.Color(0, 97, 155));
        jLabe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabe2.setText("Información Socio");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (3).png"))); // NOI18N

        jLabel_nombreReunion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion2.setText("Cedula:");

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombre.setText("...");

        labelMedidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMedidor.setText("...");

        jLabel_nombreReunion3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion3.setText("Nombre:");

        jLabel_nombreReunion4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion4.setText("Medidor:");

        labelCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCedula.setText("...");

        jLabel_nombreReunion6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion6.setText("Telefono:");

        labelTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTelefono.setText("...");

        jLabe1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabe1.setForeground(new java.awt.Color(0, 97, 155));
        jLabe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabe1.setText("Información Cobro");

        jLabe8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe8.setText("Multa por trabajo");

        multaMinga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multaMinga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        multaMinga.setText("0");
        multaMinga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multaMingaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("$");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("$");

        multaReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multaReunion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        multaReunion.setText("0");
        multaReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multaReunionActionPerformed(evt);
            }
        });

        jLabe9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe9.setText("Multa por Reunion");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N

        lecturaActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lecturaActual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lecturaActual.setText("0");
        lecturaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturaActualActionPerformed(evt);
            }
        });

        jLabe11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe11.setText("Lectura Actual");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N

        lecturaAnterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lecturaAnterior.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lecturaAnterior.setText("0");
        lecturaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturaAnteriorActionPerformed(evt);
            }
        });

        jLabe13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe13.setText("Lectura Anterior");

        diferencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diferencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diferencia.setText("0");
        diferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diferenciaActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N

        jLabe16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe16.setText("Diferencia");

        consumoTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consumoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consumoTotal.setText("0");
        consumoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoTotalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("$");

        jLabe14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe14.setText("Base");

        recargoExcesoConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recargoExcesoConsumo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        recargoExcesoConsumo.setText("0");
        recargoExcesoConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargoExcesoConsumoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("$");

        jLabe18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe18.setText("Recargo exceso consumo");

        jLabe19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe19.setText("Meses que debe");

        mesesquedebe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mesesquedebe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mesesquedebe.setText("0");
        mesesquedebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesesquedebeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("$");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("$");

        ValorMesesDebe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ValorMesesDebe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ValorMesesDebe.setText("0");
        ValorMesesDebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorMesesDebeActionPerformed(evt);
            }
        });

        jLabe15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe15.setText("Valor que debe");

        recargoMeses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recargoMeses.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        recargoMeses.setText("0");
        recargoMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargoMesesActionPerformed(evt);
            }
        });

        jLabe10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe10.setText("Recargo por meses adeudados");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("$");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("$");

        jTextReinstalacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextReinstalacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextReinstalacion.setText("0");
        jTextReinstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextReinstalacionActionPerformed(evt);
            }
        });

        jLabe17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe17.setText("Multa por Reinstalación");

        Total.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 0, 0));
        Total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Total.setText("0");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("$");

        jLabe7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabe7.setForeground(new java.awt.Color(255, 0, 0));
        jLabe7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe7.setText("TOTAL");

        jButton_imprimir1.setBackground(new java.awt.Color(0, 97, 155));
        jButton_imprimir1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_imprimir1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_imprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jButton_imprimir1.setText("Imprimir Factura");
        jButton_imprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_nombreReunion)
                        .addGap(17, 17, 17)
                        .addComponent(jTextField_codigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_buscarUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabe, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(fechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_nombreReunion1)
                        .addGap(455, 455, 455)
                        .addComponent(jButton_buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel_nombreReunion3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(labelMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel_nombreReunion6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabe2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel_nombreReunion2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel_nombreReunion4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabe1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(multaMinga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabe8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabe9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(multaReunion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabe11, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lecturaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabe13, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lecturaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabe16, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(diferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(consumoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabe14, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabe18, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabe19, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(recargoExcesoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mesesquedebe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(ValorMesesDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabe15, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabe10, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(recargoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabe17, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(330, 330, 330)
                                                .addComponent(jTextReinstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_imprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabe7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(200, 200, 200)
                                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nombreReunion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_codigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscarUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nombreReunion1)
                    .addComponent(jButton_buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombreReunion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombreReunion6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel_nombreReunion2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel_nombreReunion4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabe1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multaMinga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabe8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(multaReunion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lecturaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lecturaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consumoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabe14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(recargoExcesoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabe18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mesesquedebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabe19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorMesesDebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabe15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recargoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextReinstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabe2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton_imprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_codigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codigoUsuarioActionPerformed

    private void jButton_buscarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuario2ActionPerformed
        int cont = 0;
        if (jTextField_codigoUsuario.getText().isEmpty()) {
            cont++;
            JOptionPane.showMessageDialog(this, "Debe llenar ingresar el Socio");
        }
        if (fechaCobro.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fecha");
            cont++;
        }
        if (cont == 0) {
            try {

                // boton para llenar en la base
                ArrayList Resultados = new ArrayList();
                metodos m = new metodos();
                String nombre = jTextField_codigoUsuario.getText();
                if (isNumeric(nombre)) {
                    Resultados = m.obtenerInformacionSocioCod(nombre);
                } else {
                    Resultados = m.obtenerInformacionSocioNombre(nombre);
                }
                if (!Resultados.isEmpty()) {
                    llenarTabla(Resultados);
                } else {
                    JOptionPane.showMessageDialog(this, "USUARIO NO REGISTRADO");
                }
            } catch (SQLException | IOException ex) {
                Logger.getLogger(realizarCobros1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_buscarUsuario2ActionPerformed

    private void jButton_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuarioActionPerformed
        // boton aceptar
        ArrayList Resultados = new ArrayList();
        ArrayList datosConsumo = new ArrayList();
        ArrayList datos_multaMeses = new ArrayList();
        String strResultado = modelo.getValueAt(TablaPersonas.getSelectedRow(), 0).toString();
        System.out.println(strResultado);
        metodos m = new metodos();
        Calendar calendario = Calendar.getInstance();
        factura = new ArrayList<>();
        int año = fechaCobro.getCalendar().get(Calendar.YEAR);
        int mes = fechaCobro.getCalendar().get(Calendar.MARCH);
        int dia = fechaCobro.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mesActual = fechaCobro.getCalendar().get(Calendar.MARCH) + 1;
        String fecha1 = (año + "-" + mesActual + "-" + dia);
        calendario.set(año, mes, 1);
        int ultimoDiaMes = calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
        String fecha = (año + "-" + mesActual + "-" + ultimoDiaMes);

        System.out.println("esta feha se esta guardando " + fecha1);
        try {
            Resultados = m.obtenerInformacionSocioCodigoConsumo(strResultado);
            cod = Integer.parseInt((String) Resultados.get(0));
            idSocioConsultas = cod;
            datosConsumo = m.obtenerPagoConsumo(cod, mesActual, año);
            datos_multaMeses = m.multaMeses(fecha, cod);
            Reinstalacion = m.Reinstalacion(cod);
            labelCedula.setText((String) Resultados.get(1));
            labelMedidor.setText((String) Resultados.get(2));
            labelNombre.setText((String) Resultados.get(3));
            labelTelefono.setText((String) Resultados.get(4));
            factura.add("Cliente: ");
            factura.add((String) Resultados.get(2));
            factura.add("Fecha: ");
            factura.add(fecha1);
            factura.add("R.U.C/C.I: ");
            factura.add((String) Resultados.get(3));
            factura.add("Telefono: ");
            factura.add((String) Resultados.get(4));
            factura.add("No. Medidor");
            factura.add("Lec.Anterior");
            factura.add("Lec.Actual");
            factura.add("Consumo");
            factura.add("Codigo");
            factura.add("Consumo de");
            multaxReunion = m.obtenerMultasReuniones(cod, fecha);
            multaReunion.setText(Double.toString(multaxReunion));
            multaTrabajo = m.obtenerMultasTrabajos(cod, fecha);
            multaMinga.setText(Double.toString(multaTrabajo));
            lecturaA = Double.parseDouble((String) datosConsumo.get(0));
            lecturaAnterior.setText((String) datosConsumo.get(0));
            lecturaN = Double.parseDouble((String) datosConsumo.get(1));
            lecturaActual.setText((String) datosConsumo.get(1));
            difConsumo = (Double) datosConsumo.get(2);
            diferencia.setText(Double.toString((double) datosConsumo.get(2)));
            totalSoloConsumo = (Double) datosConsumo.get(3);
            consumoTotal.setText(Double.toString((double) datosConsumo.get(3)));
            excesoConsumo = (Double) datosConsumo.get(4);
            recargoExcesoConsumo.setText(Double.toString((double) datosConsumo.get(4)));
            totalConsumo = (Double) datosConsumo.get(5);
            meses = (Double) datos_multaMeses.get(1);
            valorMesesqueDebe = (Double) datos_multaMeses.get(2);
            totalSoloMes = totalSoloConsumo + excesoConsumo;
            total = totalSoloMes + meses + multaxReunion + multaTrabajo + valorMesesqueDebe + Reinstalacion;
            System.out.println("TOTAL" + total);
            recargoMeses.setText(Double.toString((double) datos_multaMeses.get(1)));
            mesesquedebe.setText(Double.toString((double) datos_multaMeses.get(0)));
            ValorMesesDebe.setText(Double.toString((double) datos_multaMeses.get(2)));
            mesesQueDebe = (double) datos_multaMeses.get(0);
            jTextReinstalacion.setText(Double.toString(Reinstalacion));
            Total.setText(Double.toString(total));
            factura.add(llenarCeros(((String) Resultados.get(1)).length(), (String) Resultados.get(1))); //medidor
            System.out.println(llenarCeros(((String) Resultados.get(1)).length(), (String) Resultados.get(1)));
            factura.add(llenarCeros(((String) datosConsumo.get(0)).length(), (String) datosConsumo.get(0))); // anterior
            System.out.println(llenarCeros(((String) datosConsumo.get(0)).length(), (String) datosConsumo.get(0)));
            factura.add(llenarCeros(((String) datosConsumo.get(1)).length(), (String) datosConsumo.get(1))); // actual
            System.out.println(llenarCeros(((String) datosConsumo.get(1)).length(), (String) datosConsumo.get(1)));
            factura.add(Double.toString((double) datosConsumo.get(2)));
            factura.add(Integer.toString(idSocioConsultas));
            factura.add(mesActual + "/" + año);
            factura.add("Basico: ");
            factura.add(Double.toString((double) datosConsumo.get(3)));
            factura.add("Multa x Minga: ");
            factura.add(Double.toString(multaTrabajo));
            factura.add("Multa x Asamblea: ");
            factura.add(Double.toString(multaxReunion));
            factura.add("Multa x Exc. Con.: ");
            factura.add(Double.toString((double) datosConsumo.get(4)));
            factura.add("Recargos: ");
            factura.add(Double.toString((double) datos_multaMeses.get(2)));
            factura.add("Cantidad Meses: ");
            factura.add(Double.toString((double) datos_multaMeses.get(0)));
            factura.add("SUBTOTAL $ ");
            factura.add("DESCUENTO $ ");
            factura.add("I.V.A $ ");
            factura.add("TOTAL $ ");
            factura.add("Recargo Meses:");
            factura.add(Double.toString((double) datos_multaMeses.get(1)));
            factura.add(Double.toString(total));
            factura.add("Multa por reinstalacion:");
            factura.add(Double.toString(Reinstalacion));
            System.out.println(Arrays.toString(factura.toArray()));

        } catch (SQLException | IOException ex) {
            Logger.getLogger(realizarCobros1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_buscarUsuarioActionPerformed

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    
    private void multaMingaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multaMingaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multaMingaActionPerformed

    private void multaReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multaReunionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multaReunionActionPerformed

    private void lecturaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturaActualActionPerformed

    private void lecturaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturaAnteriorActionPerformed

    private void diferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diferenciaActionPerformed

    private void consumoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoTotalActionPerformed

    private void recargoExcesoConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargoExcesoConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recargoExcesoConsumoActionPerformed

    private void mesesquedebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesesquedebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesesquedebeActionPerformed

    private void ValorMesesDebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorMesesDebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorMesesDebeActionPerformed

    private void recargoMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargoMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recargoMesesActionPerformed

    private void jTextReinstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextReinstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextReinstalacionActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void jButton_imprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimir1ActionPerformed
        try {
            // actualizar estados de las tablas
            // 0 NO PAGADO
            // 1 PAGADO
            int año = fechaCobro.getCalendar().get(Calendar.YEAR);
            int mes = fechaCobro.getCalendar().get(Calendar.MARCH);
            int mesActual = fechaCobro.getCalendar().get(Calendar.MARCH)+1;
            int dia = fechaCobro.getCalendar().get(Calendar.DAY_OF_MONTH);
            Calendar calendario = Calendar.getInstance();
            calendario.set(año, mes, 1);
            int ultimoDiaMes=calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
            String fecha = (año + "-" + mesActual + "-" + dia);
            String fecha1 = (año + "-" + mesActual + "-" + ultimoDiaMes);
            System.out.println(fecha);
            //acutalizar tablas
            metodos m = new metodos();
            m.actualizarMultasReunion(fecha, idSocioConsultas);
            m.actualizarMultasTrabajo(fecha, idSocioConsultas);
            m.actualizarPagos(fecha1, idSocioConsultas);
            m.guardarFactura(cod, fecha, 0, difConsumo, multaTrabajo, multaxReunion, totalSoloConsumo, excesoConsumo, totalSoloMes, mesesQueDebe, valorMesesqueDebe, meses, Reinstalacion, total);
            m.imprimirFactura(factura);
        } catch (SQLException | FileNotFoundException ex) {
            Logger.getLogger(realizarCobros1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(realizarCobros1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_imprimir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(realizarCobros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(realizarCobros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(realizarCobros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(realizarCobros1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new realizarCobros1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPersonas;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField ValorMesesDebe;
    private javax.swing.JTextField consumoTotal;
    private javax.swing.JTextField diferencia;
    private com.toedter.calendar.JDateChooser fechaCobro;
    private javax.swing.JButton jButton_buscarUsuario;
    private javax.swing.JButton jButton_buscarUsuario2;
    private javax.swing.JButton jButton_imprimir1;
    private javax.swing.JLabel jLabe;
    private javax.swing.JLabel jLabe1;
    private javax.swing.JLabel jLabe10;
    private javax.swing.JLabel jLabe11;
    private javax.swing.JLabel jLabe13;
    private javax.swing.JLabel jLabe14;
    private javax.swing.JLabel jLabe15;
    private javax.swing.JLabel jLabe16;
    private javax.swing.JLabel jLabe17;
    private javax.swing.JLabel jLabe18;
    private javax.swing.JLabel jLabe19;
    private javax.swing.JLabel jLabe2;
    private javax.swing.JLabel jLabe7;
    private javax.swing.JLabel jLabe8;
    private javax.swing.JLabel jLabe9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_nombreReunion;
    private javax.swing.JLabel jLabel_nombreReunion1;
    private javax.swing.JLabel jLabel_nombreReunion2;
    private javax.swing.JLabel jLabel_nombreReunion3;
    private javax.swing.JLabel jLabel_nombreReunion4;
    private javax.swing.JLabel jLabel_nombreReunion6;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField_codigoUsuario;
    private javax.swing.JTextField jTextReinstalacion;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelMedidor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTextField lecturaActual;
    private javax.swing.JTextField lecturaAnterior;
    private javax.swing.JTextField mesesquedebe;
    private javax.swing.JTextField multaMinga;
    private javax.swing.JTextField multaReunion;
    private javax.swing.JTextField recargoExcesoConsumo;
    private javax.swing.JTextField recargoMeses;
    // End of variables declaration//GEN-END:variables
}
