/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import com.itextpdf.text.DocumentException;
import java.awt.ScrollPane;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import static vista.registrarAsistenciasReuniones.isNumeric;

/**
 *
 * @author Kami Osita Bebe
 */
public class realizarCobros extends javax.swing.JFrame {

    DefaultTableModel modelo;
    int idSocioConsultas = 0;
    static int cod = 0;
    static double multaxReunion = 0, multaTrabajo = 0;
    static double lecturaA = 0;
    static double lecturaN = 0;
    static double totalSoloConsumo = 0.0;
    static double excesoConsumo = 0.0;
    static double totalConsumo = 0.0;
    static double difConsumo;
    static double meses = 0.0;
    static double total = 0.0;
    static double totalSoloMes = 0.0;
    static double valorMesesqueDebe = 0.0;
    static double mesesQueDebe = 0.0;
    static double Reinstalacion = 0.0;
    ArrayList<String> factura;
    JScrollPane scrollPane;
    
    /**
     *
     * Creates new form login
     */
    public realizarCobros() {
        this.setResizable(false);
        initComponents();
        setTitle("Realizar Cobros");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        deshabilitarText();
        scrollPane=new JScrollPane();
    }

    public void deshabilitarText() {
        lecturaActual.setEditable(false);
        lecturaAnterior.setEditable(false);
        multaMinga.setEditable(false);
        multaReunion.setEditable(false);
        recargoExcesoConsumo.setEditable(false);
        ValorMesesDebe.setEditable(false);
        Total.setEditable(false);
        consumoTotal.setEditable(false);
    }

    public void llenarTabla(ArrayList Resultados) {
        modelo = new DefaultTableModel() {
            public boolean isCellEditable(int filas, int columnas) {
                if (columnas == 2) {
                    return true;
                } else {
                    return false;
                }
            }
            //modelo.getColumnModel().getColumn(0).setPreferredWidth(20);
        };

        modelo.addColumn("Nombre");
        modelo.addColumn("Codigo");

        TablaPersonas.setModel(modelo);
        for (int i = 0; i < Resultados.size() - 1; i += 2) {
            modelo.addRow(new Object[]{Resultados.get(i + 1), Resultados.get(i)});
            // System.out.println(valores.get(i));
        }
    }

    public String llenarCeros(int tamanio, String original) {
        String cero = "";
        for (int i = tamanio; i < 6; i++) {
            cero = cero + "0";
        }
        return cero + original;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup_asistencias = new javax.swing.ButtonGroup();
        jLabe12 = new javax.swing.JLabel();
        lecturaAnterior = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPersonas = new javax.swing.JTable();
        jTextField_codigoUsuario = new javax.swing.JTextField();
        jButton_buscarUsuario = new javax.swing.JButton();
        jLabel_nombreReunion = new javax.swing.JLabel();
        jButton_buscarUsuario2 = new javax.swing.JButton();
        jLabel_nombreReunion1 = new javax.swing.JLabel();
        fechaCobro = new com.toedter.calendar.JDateChooser();
        jLabe = new javax.swing.JLabel();
        jLabe2 = new javax.swing.JLabel();
        jLabe1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_nombreReunion2 = new javax.swing.JLabel();
        jLabel_nombreReunion3 = new javax.swing.JLabel();
        jLabel_nombreReunion4 = new javax.swing.JLabel();
        jLabel_nombreReunion6 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelMedidor = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        jLabe8 = new javax.swing.JLabel();
        jLabe9 = new javax.swing.JLabel();
        jLabe11 = new javax.swing.JLabel();
        jLabe13 = new javax.swing.JLabel();
        jLabe16 = new javax.swing.JLabel();
        multaMinga = new javax.swing.JTextField();
        multaReunion = new javax.swing.JTextField();
        lecturaActual = new javax.swing.JTextField();
        diferencia = new javax.swing.JTextField();
        consumoTotal = new javax.swing.JTextField();
        recargoExcesoConsumo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mesesquedebe = new javax.swing.JTextField();
        ValorMesesDebe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        recargoMeses = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabe14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabe18 = new javax.swing.JLabel();
        jLabe19 = new javax.swing.JLabel();
        jLabe15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabe10 = new javax.swing.JLabel();
        jLabe7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabe17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_imprimir1 = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        jTextReinstalacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabe12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe12.setText("Recargo:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(950, 725));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturaAnterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lecturaAnterior.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lecturaAnterior.setText("0");
        lecturaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturaAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(lecturaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 150, -1));

        TablaPersonas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPersonas.setFocusable(false);
        jScrollPane1.setViewportView(TablaPersonas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 890, 110));

        jTextField_codigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_codigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_codigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 440, 30));

        jButton_buscarUsuario.setBackground(new java.awt.Color(0, 97, 155));
        jButton_buscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick.png"))); // NOI18N
        jButton_buscarUsuario.setText("Aceptar");
        jButton_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 130, 30));

        jLabel_nombreReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion.setText("Ingrese el nombre o código del socio");
        getContentPane().add(jLabel_nombreReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        jButton_buscarUsuario2.setBackground(new java.awt.Color(30, 139, 204));
        jButton_buscarUsuario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jButton_buscarUsuario2.setText("Buscar");
        jButton_buscarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscarUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 131, -1));

        jLabel_nombreReunion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_nombreReunion1.setText("Seleccione el usuario que desea*.");
        getContentPane().add(jLabel_nombreReunion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        fechaCobro.setDateFormatString("yyyy-MM-dd");
        fechaCobro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(fechaCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 580, 30));

        jLabe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe.setText("Seleccione fecha de pago");
        getContentPane().add(jLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 212, 27));

        jLabe2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabe2.setForeground(new java.awt.Color(0, 97, 155));
        jLabe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabe2.setText("Información Socio");
        getContentPane().add(jLabe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 360, 37));

        jLabe1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabe1.setForeground(new java.awt.Color(0, 97, 155));
        jLabe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabe1.setText("Información Cobro");
        getContentPane().add(jLabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 500, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (3).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 200, 220));

        jLabel_nombreReunion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion2.setText("Cédula");
        getContentPane().add(jLabel_nombreReunion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 100, 30));

        jLabel_nombreReunion3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion3.setText("Nombre");
        getContentPane().add(jLabel_nombreReunion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 80, 30));

        jLabel_nombreReunion4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion4.setText("Medidor");
        getContentPane().add(jLabel_nombreReunion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 80, 30));

        jLabel_nombreReunion6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion6.setText("Teléfono");
        getContentPane().add(jLabel_nombreReunion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 90, 30));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombre.setText("...");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 300, 30));

        labelMedidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMedidor.setText("...");
        getContentPane().add(labelMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 290, 30));

        labelCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCedula.setText("...");
        getContentPane().add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 231, 27));

        labelTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTelefono.setText("...");
        getContentPane().add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 231, 27));

        jLabe8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe8.setText("Multa por trabajo");
        getContentPane().add(jLabe8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 370, 30));

        jLabe9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe9.setText("Multa por Reunión");
        getContentPane().add(jLabe9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 350, 30));

        jLabe11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe11.setText("Lectura Actual");
        getContentPane().add(jLabe11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 330, 30));

        jLabe13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe13.setText("Lectura Anterior");
        getContentPane().add(jLabe13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 330, 30));

        jLabe16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe16.setText("Diferencia");
        getContentPane().add(jLabe16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 330, 30));

        multaMinga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multaMinga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        multaMinga.setText("0");
        multaMinga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multaMingaActionPerformed(evt);
            }
        });
        getContentPane().add(multaMinga, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 150, -1));

        multaReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multaReunion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        multaReunion.setText("0");
        multaReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multaReunionActionPerformed(evt);
            }
        });
        getContentPane().add(multaReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 150, -1));

        lecturaActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lecturaActual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lecturaActual.setText("0");
        lecturaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturaActualActionPerformed(evt);
            }
        });
        getContentPane().add(lecturaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 150, -1));

        diferencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diferencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diferencia.setText("0");
        diferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(diferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 150, -1));

        consumoTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consumoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consumoTotal.setText("0");
        consumoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoTotalActionPerformed(evt);
            }
        });
        getContentPane().add(consumoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 150, -1));

        recargoExcesoConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recargoExcesoConsumo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        recargoExcesoConsumo.setText("0");
        recargoExcesoConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargoExcesoConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(recargoExcesoConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("$");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, 20, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 20, 30));

        mesesquedebe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mesesquedebe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mesesquedebe.setText("0");
        mesesquedebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesesquedebeActionPerformed(evt);
            }
        });
        getContentPane().add(mesesquedebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 150, -1));

        ValorMesesDebe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ValorMesesDebe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ValorMesesDebe.setText("0");
        ValorMesesDebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorMesesDebeActionPerformed(evt);
            }
        });
        getContentPane().add(ValorMesesDebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 20, 30));

        recargoMeses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recargoMeses.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        recargoMeses.setText("0");
        recargoMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargoMesesActionPerformed(evt);
            }
        });
        getContentPane().add(recargoMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 150, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 40, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("$");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 20, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("$");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 20, 30));

        jLabe14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe14.setText("Base");
        getContentPane().add(jLabe14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 380, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 40, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metros.PNG"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 40, 30));

        jLabe18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe18.setText("Recargo exceso consumo");
        getContentPane().add(jLabe18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 380, 30));

        jLabe19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe19.setText("Meses que debe");
        getContentPane().add(jLabe19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 380, 30));

        jLabe15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe15.setText("Valor que debe");
        getContentPane().add(jLabe15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 380, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("$");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 20, 30));

        jLabe10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe10.setText("Recargo por meses adeudados");
        getContentPane().add(jLabe10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 390, 30));

        jLabe7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabe7.setForeground(new java.awt.Color(255, 0, 0));
        jLabe7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe7.setText("TOTAL");
        getContentPane().add(jLabe7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("$");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 20, 30));

        jLabe17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe17.setText("Multa por Reinstalación");
        getContentPane().add(jLabe17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 370, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 20, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 20, 340));

        jButton_imprimir1.setBackground(new java.awt.Color(0, 97, 155));
        jButton_imprimir1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_imprimir1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_imprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jButton_imprimir1.setText("Imprimir Factura");
        jButton_imprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_imprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 200, 30));

        Total.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 0, 0));
        Total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Total.setText("0");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 150, -1));

        jTextReinstalacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextReinstalacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextReinstalacion.setText("0");
        jTextReinstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextReinstalacionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextReinstalacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("$");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 10, 30));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 920, 410));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 1040, 1050));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("$");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_codigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codigoUsuarioActionPerformed

    private void jButton_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuarioActionPerformed
        // boton aceptar
        ArrayList Resultados = new ArrayList();
        ArrayList datosConsumo = new ArrayList();
        ArrayList datos_multaMeses = new ArrayList();
        String strResultado = modelo.getValueAt(TablaPersonas.getSelectedRow(), 0).toString();
        System.out.println(strResultado);
        metodos m = new metodos();
        Calendar calendario = Calendar.getInstance();
        factura = new ArrayList<>();
        int año = fechaCobro.getCalendar().get(Calendar.YEAR);
        int mes = fechaCobro.getCalendar().get(Calendar.MARCH);
        int dia = fechaCobro.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mesActual = fechaCobro.getCalendar().get(Calendar.MARCH) + 1;
        String fecha1 = (año + "-" + mesActual + "-" + dia);
        calendario.set(año, mes, 1);
        int ultimoDiaMes = calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
        String fecha = (año + "-" + mesActual + "-" + ultimoDiaMes);

        System.out.println("esta feha se esta guardando " + fecha1);
        try {
            Resultados = m.obtenerInformacionSocioCodigoConsumo(strResultado);
            cod = Integer.parseInt((String) Resultados.get(0));
            idSocioConsultas = cod;
            datosConsumo = m.obtenerPagoConsumo(cod, mesActual, año);
            datos_multaMeses = m.multaMeses(fecha, cod);
            Reinstalacion = m.Reinstalacion(cod);
            labelCedula.setText((String) Resultados.get(1));
            labelMedidor.setText((String) Resultados.get(2));
            labelNombre.setText((String) Resultados.get(3));
            labelTelefono.setText((String) Resultados.get(4));
            factura.add("Cliente: ");
            factura.add((String) Resultados.get(2));
            factura.add("Fecha: ");
            factura.add(fecha1);
            factura.add("R.U.C/C.I: ");
            factura.add((String) Resultados.get(3));
            factura.add("Telefono: ");
            factura.add((String) Resultados.get(4));
            factura.add("No. Medidor");
            factura.add("Lec.Anterior");
            factura.add("Lec.Actual");
            factura.add("Consumo");
            factura.add("Codigo");
            factura.add("Consumo de");
            multaxReunion = m.obtenerMultasReuniones(cod, fecha);
            multaReunion.setText(Double.toString(multaxReunion));
            multaTrabajo = m.obtenerMultasTrabajos(cod, fecha);
            multaMinga.setText(Double.toString(multaTrabajo));
            lecturaA = Double.parseDouble((String) datosConsumo.get(0));
            lecturaAnterior.setText((String) datosConsumo.get(0));
            lecturaN = Double.parseDouble((String) datosConsumo.get(1));
            lecturaActual.setText((String) datosConsumo.get(1));
            difConsumo = (Double) datosConsumo.get(2);
            diferencia.setText(Double.toString((double) datosConsumo.get(2)));
            totalSoloConsumo = (Double) datosConsumo.get(3);
            consumoTotal.setText(Double.toString((double) datosConsumo.get(3)));
            excesoConsumo = (Double) datosConsumo.get(4);
            recargoExcesoConsumo.setText(Double.toString((double) datosConsumo.get(4)));
            totalConsumo = (Double) datosConsumo.get(5);
            meses = (Double) datos_multaMeses.get(1);
            valorMesesqueDebe = (Double) datos_multaMeses.get(2);
            totalSoloMes = totalSoloConsumo + excesoConsumo;
            total = totalSoloMes + meses + multaxReunion + multaTrabajo + valorMesesqueDebe + Reinstalacion;
            System.out.println("TOTAL" + total);
            recargoMeses.setText(Double.toString((double) datos_multaMeses.get(1)));
            mesesquedebe.setText(Double.toString((double) datos_multaMeses.get(0)));
            ValorMesesDebe.setText(Double.toString((double) datos_multaMeses.get(2)));
            mesesQueDebe = (double) datos_multaMeses.get(0);
            jTextReinstalacion.setText(Double.toString(Reinstalacion));
            Total.setText(Double.toString(total));
            factura.add(llenarCeros(((String) Resultados.get(1)).length(), (String) Resultados.get(1))); //medidor
            System.out.println(llenarCeros(((String) Resultados.get(1)).length(), (String) Resultados.get(1)));
            factura.add(llenarCeros(((String) datosConsumo.get(0)).length(), (String) datosConsumo.get(0))); // anterior 
            System.out.println(llenarCeros(((String) datosConsumo.get(0)).length(), (String) datosConsumo.get(0)));
            factura.add(llenarCeros(((String) datosConsumo.get(1)).length(), (String) datosConsumo.get(1))); // actual
            System.out.println(llenarCeros(((String) datosConsumo.get(1)).length(), (String) datosConsumo.get(1)));
            factura.add(Double.toString((double) datosConsumo.get(2)));
            factura.add(Integer.toString(idSocioConsultas));
            factura.add(mesActual + "/" + año);
            factura.add("Basico: ");
            factura.add(Double.toString((double) datosConsumo.get(3)));
            factura.add("Multa x Minga: ");
            factura.add(Double.toString(multaTrabajo));
            factura.add("Multa x Asamblea: ");
            factura.add(Double.toString(multaxReunion));
            factura.add("Multa x Exc. Con.: ");
            factura.add(Double.toString((double) datosConsumo.get(4)));
            factura.add("Recargos: ");
            factura.add(Double.toString((double) datos_multaMeses.get(2)));
            factura.add("Cantidad Meses: ");
            factura.add(Double.toString((double) datos_multaMeses.get(0)));
            factura.add("SUBTOTAL $ ");
            factura.add("DESCUENTO $ ");
            factura.add("I.V.A $ ");
            factura.add("TOTAL $ ");
            factura.add("Recargo Meses:");
            factura.add(Double.toString((double) datos_multaMeses.get(1)));
            factura.add(Double.toString(total));
            factura.add("Multa por reinstalacion:");
            factura.add(Double.toString(Reinstalacion));
            System.out.println(Arrays.toString(factura.toArray()));

        } catch (SQLException | IOException ex) {
            Logger.getLogger(realizarCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_buscarUsuarioActionPerformed

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }


    private void jButton_buscarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuario2ActionPerformed
        int cont = 0;
        if (jTextField_codigoUsuario.getText().isEmpty()) {
            cont++;
            JOptionPane.showMessageDialog(this, "Debe llenar ingresar el Socio");
        }
        if (fechaCobro.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fecha");
            cont++;
        }
        if (cont == 0) {
            try {

                // boton para llenar en la base
                ArrayList Resultados = new ArrayList();
                metodos m = new metodos();
                String nombre = jTextField_codigoUsuario.getText();
                if (isNumeric(nombre)) {
                    Resultados = m.obtenerInformacionSocioCod(nombre);
                } else {
                    Resultados = m.obtenerInformacionSocioNombre(nombre);
                }
                if (!Resultados.isEmpty()) {
                    llenarTabla(Resultados);
                } else {
                    JOptionPane.showMessageDialog(this, "USUARIO NO REGISTRADO");
                }
            } catch (SQLException | IOException ex) {
                Logger.getLogger(realizarCobros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_buscarUsuario2ActionPerformed

    private void lecturaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturaAnteriorActionPerformed

    private void consumoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoTotalActionPerformed

    private void multaMingaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multaMingaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multaMingaActionPerformed

    private void multaReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multaReunionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multaReunionActionPerformed

    private void lecturaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturaActualActionPerformed

    private void recargoExcesoConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargoExcesoConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recargoExcesoConsumoActionPerformed

    private void ValorMesesDebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorMesesDebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorMesesDebeActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void diferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diferenciaActionPerformed

    private void mesesquedebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesesquedebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesesquedebeActionPerformed

    private void recargoMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargoMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recargoMesesActionPerformed

    private void jButton_imprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimir1ActionPerformed
        try {
            // actualizar estados de las tablas
            // 0 NO PAGADO
            // 1 PAGADO
            int año = fechaCobro.getCalendar().get(Calendar.YEAR);
            int mes = fechaCobro.getCalendar().get(Calendar.MARCH);
            int mesActual = fechaCobro.getCalendar().get(Calendar.MARCH)+1;
            int dia = fechaCobro.getCalendar().get(Calendar.DAY_OF_MONTH);
            Calendar calendario = Calendar.getInstance();
            calendario.set(año, mes, 1);
            int ultimoDiaMes=calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
            String fecha = (año + "-" + mesActual + "-" + dia);
            String fecha1 = (año + "-" + mesActual + "-" + ultimoDiaMes);
            System.out.println(fecha);
            //acutalizar tablas
            metodos m = new metodos();
            m.actualizarMultasReunion(fecha, idSocioConsultas);
            m.actualizarMultasTrabajo(fecha, idSocioConsultas);
            m.actualizarPagos(fecha1, idSocioConsultas);
            m.pagarReinstalacion(idSocioConsultas, fecha);
            m.guardarFactura(cod, fecha, 0, difConsumo, multaTrabajo, multaxReunion, totalSoloConsumo, excesoConsumo, totalSoloMes, mesesQueDebe, valorMesesqueDebe, meses, Reinstalacion, total);
            m.imprimirFactura(factura);
        } catch (SQLException | FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "FACTURA YA REGISTRADA");
            Logger.getLogger(realizarCobros.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(realizarCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_imprimir1ActionPerformed

    private void jTextReinstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextReinstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextReinstalacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(realizarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            new realizarCobros().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPersonas;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField ValorMesesDebe;
    private javax.swing.ButtonGroup buttonGroup_asistencias;
    private javax.swing.JTextField consumoTotal;
    private javax.swing.JTextField diferencia;
    private com.toedter.calendar.JDateChooser fechaCobro;
    private javax.swing.JButton jButton_buscarUsuario;
    private javax.swing.JButton jButton_buscarUsuario2;
    private javax.swing.JButton jButton_imprimir1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabe;
    private javax.swing.JLabel jLabe1;
    private javax.swing.JLabel jLabe10;
    private javax.swing.JLabel jLabe11;
    private javax.swing.JLabel jLabe12;
    private javax.swing.JLabel jLabe13;
    private javax.swing.JLabel jLabe14;
    private javax.swing.JLabel jLabe15;
    private javax.swing.JLabel jLabe16;
    private javax.swing.JLabel jLabe17;
    private javax.swing.JLabel jLabe18;
    private javax.swing.JLabel jLabe19;
    private javax.swing.JLabel jLabe2;
    private javax.swing.JLabel jLabe7;
    private javax.swing.JLabel jLabe8;
    private javax.swing.JLabel jLabe9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_nombreReunion;
    private javax.swing.JLabel jLabel_nombreReunion1;
    private javax.swing.JLabel jLabel_nombreReunion2;
    private javax.swing.JLabel jLabel_nombreReunion3;
    private javax.swing.JLabel jLabel_nombreReunion4;
    private javax.swing.JLabel jLabel_nombreReunion6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_codigoUsuario;
    private javax.swing.JTextField jTextReinstalacion;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelMedidor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTextField lecturaActual;
    private javax.swing.JTextField lecturaAnterior;
    private javax.swing.JTextField mesesquedebe;
    private javax.swing.JTextField multaMinga;
    private javax.swing.JTextField multaReunion;
    private javax.swing.JTextField recargoExcesoConsumo;
    private javax.swing.JTextField recargoMeses;
    // End of variables declaration//GEN-END:variables
}
