/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.asistenciaReunion;
import logica.manejador;

/**
 *
 * @author Kami Osita Bebe
 */
public class registrarAsistenciasReuniones extends javax.swing.JDialog {

    public metodos metodos = new metodos();

    /**
     * Creates new form login
     */
    public registrarAsistenciasReuniones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("Registar Asistencias Reuniones");
        this.setResizable(false);
        setLocationRelativeTo(null);
        llenarCombo();
        try {
            obtenerUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(registrarAsistenciasReuniones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup_asistencias = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_fechaReunion = new javax.swing.JLabel();
        jComboBox_reuniones = new javax.swing.JComboBox<String>();
        jLabel_reunion = new javax.swing.JLabel();
        jTextField_nombreReunion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_nombreReunion = new javax.swing.JLabel();
        jTextField_codigoUsuario = new javax.swing.JTextField();
        jButton_buscarUsuario = new javax.swing.JButton();
        jLabel_reunion3 = new javax.swing.JLabel();
        jLabel_nombreReunion2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButton_Asiste = new javax.swing.JRadioButton();
        jRadioButton_Atraso = new javax.swing.JRadioButton();
        jButton_guardarAsistencia = new javax.swing.JButton();
        jLabel_nombreReunion1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(776, 635));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 740, 10));

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 30)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Registrar Asistencias");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, -1));

        jLabel_fechaReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_fechaReunion.setText("Seleccione una reunión por su fecha:");
        getContentPane().add(jLabel_fechaReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 37));

        jComboBox_reuniones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_reuniones.setBorder(null);
        jComboBox_reuniones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_reunionesItemStateChanged(evt);
            }
        });
        jComboBox_reuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_reunionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_reuniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 420, -1));

        jLabel_reunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_reunion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_reunion.setText("Nombre de la reunión:");
        getContentPane().add(jLabel_reunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 30));

        jTextField_nombreReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_nombreReunion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_nombreReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreReunionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_nombreReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 530, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 740, 10));

        jLabel_nombreReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion.setText("Ingrese el código o nombre del usuario a buscar");
        getContentPane().add(jLabel_nombreReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 566, 43));

        jTextField_codigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_codigoUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_codigoUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_codigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_codigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 580, 40));

        jButton_buscarUsuario.setBackground(new java.awt.Color(30, 139, 204));
        jButton_buscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jButton_buscarUsuario.setText("Buscar");
        jButton_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 128, 39));

        jLabel_reunion3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel_reunion3.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_reunion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_reunion3.setText("Socios");
        getContentPane().add(jLabel_reunion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 560, 30));

        jLabel_nombreReunion2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_nombreReunion2.setText("Seleccione el usuario que desea*.");
        getContentPane().add(jLabel_nombreReunion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 260, 43));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombres", "Apellidos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 287, 560, 240));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 17, 210));

        buttonGroup_asistencias.add(jRadioButton_Asiste);
        jRadioButton_Asiste.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton_Asiste.setText("A tiempo");
        getContentPane().add(jRadioButton_Asiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        buttonGroup_asistencias.add(jRadioButton_Atraso);
        jRadioButton_Atraso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton_Atraso.setText("Atrasado");
        getContentPane().add(jRadioButton_Atraso, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jButton_guardarAsistencia.setBackground(new java.awt.Color(0, 97, 155));
        jButton_guardarAsistencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_guardarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton_guardarAsistencia.setText("Guardar");
        jButton_guardarAsistencia.setBorder(null);
        jButton_guardarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarAsistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 125, 39));

        jLabel_nombreReunion1.setText("Seleccione el usuario que desea*.");
        getContentPane().add(jLabel_nombreReunion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 740, 520));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuarioActionPerformed
        obtenerUsuario();
    }//GEN-LAST:event_jButton_buscarUsuarioActionPerformed

    public void obtenerUsuario() {
        String codigoUsuario = jTextField_codigoUsuario.getText();
        ArrayList<String> usuario = new ArrayList<>();
        if (isNumeric(codigoUsuario)) {
            try {
                usuario = metodos.obtenerUnicoUsuario(codigoUsuario);
                if (usuario.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese ID");

                }
            } catch (SQLException ex) {
                Logger.getLogger(registrarAsistenciasReuniones.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("USUARIO NO EXISTE");
            }
        } else {
            try {
                usuario = metodos.obtenerUsuarios(codigoUsuario);
                if (usuario.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No Existen usuarios con ese Nombre");
                }
            } catch (SQLException ex) {
                Logger.getLogger(registrarAsistenciasReuniones.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("USUARIO NO EXISTE");

            }
        }
        if (!usuario.isEmpty()) {
            DefaultTableModel modelo;
            modelo = new DefaultTableModel() {
                public boolean isCellEditable(int filas, int columnas) {
                    return false;
                }
            };
            modelo.addColumn("Nombre");
            jTable1.setModel(modelo);
            for (int i = 0; i < usuario.size(); i++) {
                modelo.addRow(new Object[]{usuario.get(i)});
            }

        } else {

            DefaultTableModel modelo;
            modelo = new DefaultTableModel();
            modelo.addColumn("Nombre");
            jTable1.setModel(modelo);
        }
    }

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    private void jComboBox_reunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_reunionesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox_reunionesActionPerformed

    private void jTextField_nombreReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreReunionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreReunionActionPerformed

    private void jTextField_codigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoUsuarioActionPerformed
        obtenerUsuario();
    }//GEN-LAST:event_jTextField_codigoUsuarioActionPerformed

    private void jButton_guardarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarAsistenciaActionPerformed
        jRadioButton_Asiste.setActionCommand("Asiste");
        jRadioButton_Atraso.setActionCommand("Atraso");
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        int fila = jTable1.getSelectedRow();
        int id = 0, asistencia = 0;
        String nombres, registro;
        String fecha = (String) jComboBox_reuniones.getSelectedItem();
        manejador mn = new manejador();
        if (fila >= 0) {
            nombres = String.valueOf(tm.getValueAt(jTable1.getSelectedRow(), 0));
            registro = buttonGroup_asistencias.getSelection().getActionCommand();
            try {
                id = Integer.parseInt(metodos.obtenerID(nombres));
            } catch (SQLException ex) {
                Logger.getLogger(registrarAsistenciasReuniones.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (registro.equals("Asiste")) {
                asistencia = 2;
            } else if (registro.equals("Atraso")) {
                asistencia = 1;
            }

            try {
                metodos.crearRegistroAsistencia(id, fecha, asistencia, 0);
                jTextField_codigoUsuario.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(registrarAsistenciasReuniones.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario ");
        }
    }//GEN-LAST:event_jButton_guardarAsistenciaActionPerformed

    public void llenarCombo() {
        ArrayList<String> fecha = new ArrayList<>();
        try {
            fecha = metodos.obtenerReuniones();
            for (int i = 0; i < fecha.size(); i++) {
                jComboBox_reuniones.addItem(fecha.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(verReunion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void obtenerInformacion() throws SQLException {
        ArrayList<String> informacion = new ArrayList<>();
        String fecha = (String) jComboBox_reuniones.getSelectedItem();
        informacion = metodos.obtenerInformacionReunion(fecha);
        jTextField_nombreReunion.setText(informacion.get(0));

    }

    public void obtenerUsuarios() throws SQLException {
        ArrayList<String> usuarios = new ArrayList<>();
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        jTable1.setModel(modelo);
        for (int i = 0; i < usuarios.size() - 1; i = i + 2) {
            modelo.addRow(new Object[]{usuarios.get(i), usuarios.get(i + 1)});
        }
    }

    private void jComboBox_reunionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_reunionesItemStateChanged
        try {
            obtenerInformacion();
        } catch (SQLException ex) {
            Logger.getLogger(verReunion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox_reunionesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarAsistenciasReuniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                crearReunion dialog = new crearReunion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_asistencias;
    private javax.swing.JButton jButton_buscarUsuario;
    private javax.swing.JButton jButton_guardarAsistencia;
    private javax.swing.JComboBox<String> jComboBox_reuniones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_fechaReunion;
    private javax.swing.JLabel jLabel_nombreReunion;
    private javax.swing.JLabel jLabel_nombreReunion1;
    private javax.swing.JLabel jLabel_nombreReunion2;
    private javax.swing.JLabel jLabel_reunion;
    private javax.swing.JLabel jLabel_reunion3;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JRadioButton jRadioButton_Asiste;
    private javax.swing.JRadioButton jRadioButton_Atraso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_codigoUsuario;
    private javax.swing.JTextField jTextField_nombreReunion;
    // End of variables declaration//GEN-END:variables
}
