/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kami Osita Bebe
 */
public class registrarConsumo extends javax.swing.JFrame {

    metodos metodos = new metodos();

    /**
     * Creates new form login
     */
    public registrarConsumo() {
        initComponents();
        this.setResizable(false);
//        this.setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Asistencias");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup_asistencias = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel_titulo = new javax.swing.JLabel();
        jDateChooser_selectorFechaTrabajo = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton_cargarDatosConsumo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSocioConsumo = new javax.swing.JTable();
        jButton_guardarConsumo = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(1044, 717));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Registar Consumo");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 990, -1));

        jDateChooser_selectorFechaTrabajo.setDateFormatString("yyyy-MM-dd");
        jDateChooser_selectorFechaTrabajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jDateChooser_selectorFechaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 630, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fecha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 100, 27));

        jButton_cargarDatosConsumo.setBackground(new java.awt.Color(0, 97, 155));
        jButton_cargarDatosConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_cargarDatosConsumo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cargarDatosConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar-chart-reload.png"))); // NOI18N
        jButton_cargarDatosConsumo.setText("Cargar Datos");
        jButton_cargarDatosConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cargarDatosConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cargarDatosConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        TablaSocioConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TablaSocioConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Num. Medidor", "Nombre", "Consumo Anterior", "Consumo Actual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaSocioConsumo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 983, 530));

        jButton_guardarConsumo.setBackground(new java.awt.Color(0, 97, 155));
        jButton_guardarConsumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_guardarConsumo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardarConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton_guardarConsumo.setText("Guardar");
        jButton_guardarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardarConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 630, 150, 39));

        Modificar.setBackground(new java.awt.Color(0, 97, 155));
        Modificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/writing (1).png"))); // NOI18N
        Modificar.setText("Modificar Cosumos");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 230, 39));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 36, 983, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/otroFondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 960));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarConsumoActionPerformed
        // TODO add your handling code here:ArrayList<String> valores = new ArrayList<>();

        int año = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.YEAR);
        int mes = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.MARCH);
        int mesActual = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.MARCH) + 1;
        Calendar calendario = Calendar.getInstance();
        calendario.set(año, mes, 1);
        int ultimoDiaMes = calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
        String fecha = (año + "-" + mesActual + "-" + ultimoDiaMes);
        int fila = TablaSocioConsumo.getRowCount();
        int i;
        ArrayList<Object> valores = new ArrayList<>();
        valores.add(fecha);
        int cont = 0;
        for (i = 0; i < fila; i++) {
            if ((String) TablaSocioConsumo.getValueAt(i, 4) != null) {
                String codigo = (String) TablaSocioConsumo.getValueAt(i, 0);
                String consumoAn = (String) TablaSocioConsumo.getValueAt(i, 3);
                String consumoA = (String) TablaSocioConsumo.getValueAt(i, 4);
                if (isNumeric(TablaSocioConsumo.getValueAt(i, 4).toString())) {
                    double diferencia = Double.parseDouble(consumoA) - Double.parseDouble(consumoAn);
                    valores.add(codigo);
                    valores.add(diferencia);
                    valores.add(consumoA);

                } else {
                    JOptionPane.showMessageDialog(null, "ERROR EN LOS VALORES, PUEDEN QUE CONTENGAN LETRAS", "Alerta!", JOptionPane.ERROR_MESSAGE);
                    cont++;
                }
            } else {
                JOptionPane.showMessageDialog(null, "HAY CAMPOS VACIOS, AGREGAR TODOS LOS VALORES", "Alerta!", JOptionPane.ERROR_MESSAGE);
                cont++;
            }
        }
        if (cont == 0) {
            try {
                metodos.registrarConsumo(valores);
                JOptionPane.showMessageDialog(this, "CONSUMOS REGISTRADOS CORRECTAMENTE");
                System.out.println("EXITO");
                metodos.registrarPagos(valores);
            } catch (SQLException ex) {
                //Logger.getLogger(registrarConsumo.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Consumos ya registrados si desea modificar ingrese en MODIFICAR CONSUMOS", "Alerta!", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton_guardarConsumoActionPerformed

    private void jButton_cargarDatosConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cargarDatosConsumoActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_jButton_cargarDatosConsumoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:

        modificarConsumos mc = new modificarConsumos();
        mc.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    public void cargarDatos() {
        ArrayList<String> valores = new ArrayList<>();
        int anio = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.YEAR);
        int mes = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.MONTH) + 1;
        System.out.println("MEEES" + mes);
        int dia = jDateChooser_selectorFechaTrabajo.getCalendar().get(Calendar.DAY_OF_MONTH);
        System.out.println();
        try {
            valores = metodos.informacionSocioConsumoAnterior(mes, anio);
            DefaultTableModel modelo;
            modelo = new DefaultTableModel() {
                public boolean isCellEditable(int filas, int columnas) {
                    if (columnas == 4) {
                        return true;
                    } else {
                        return false;
                    }
                }
            };

            modelo.addColumn("Codigo");
            modelo.addColumn("Num. Medidor");
            modelo.addColumn("Usuario");
            modelo.addColumn("Consumo Anterior");
            modelo.addColumn("Consumo Actual");
            TablaSocioConsumo.setModel(modelo);

            for (int i = 0; i < valores.size() - 1; i = i + 4) {
                modelo.addRow(new Object[]{valores.get(i), valores.get(i + 1), valores.get(i + 2), valores.get(i + 3)});
                // System.out.println(valores.get(i));
            }
            int[] anchos = {40, 40, 200, 40, 40};

            for (int i = 0; i < TablaSocioConsumo.getColumnCount(); i++) {
                TablaSocioConsumo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);

            }
        } catch (SQLException ex) {
            Logger.getLogger(informacionReuniones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Double.parseDouble(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new registrarConsumo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JTable TablaSocioConsumo;
    private javax.swing.ButtonGroup buttonGroup_asistencias;
    private javax.swing.JButton jButton_cargarDatosConsumo;
    private javax.swing.JButton jButton_guardarConsumo;
    private com.toedter.calendar.JDateChooser jDateChooser_selectorFechaTrabajo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
