/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.asistenciaReunion;
import logica.manejador;

/**
 *
 * @author Kami Osita Bebe
 */
public class Reinstalacion1 extends javax.swing.JDialog {

    public metodos metodos = new metodos();

    /**
     * Creates new form login
     */
    public Reinstalacion1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Multa Reinstalacion");
        this.setResizable(false);
        setLocationRelativeTo(null);
        try {
            obtenerUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(Reinstalacion1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup_asistencias = new javax.swing.ButtonGroup();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nombreReunion4 = new javax.swing.JLabel();
        jLabel_nombreReunion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_codigoUsuario = new javax.swing.JTextField();
        jButton_buscarUsuario = new javax.swing.JButton();
        ValorReingreso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_reunion3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_nombreReunion2 = new javax.swing.JLabel();
        jButton_guardarAsistencia = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabe = new javax.swing.JLabel();
        fechaCobro = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel_nombreReunion3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 460));
        setMinimumSize(new java.awt.Dimension(610, 461));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Registrar Multa por Reinstalación");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, -1));

        jLabel_nombreReunion4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_nombreReunion4.setText("Seleccione el usuario que desea*.");
        getContentPane().add(jLabel_nombreReunion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, 43));

        jLabel_nombreReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion.setText("Ingrese el costo de reingreso.");
        getContentPane().add(jLabel_nombreReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 260, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 580, 10));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 410));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 550, 10));

        jTextField_codigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_codigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_codigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 410, 40));

        jButton_buscarUsuario.setBackground(new java.awt.Color(30, 139, 204));
        jButton_buscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_buscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jButton_buscarUsuario.setText("Buscar");
        jButton_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 128, 39));

        ValorReingreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ValorReingreso.setForeground(new java.awt.Color(255, 0, 0));
        ValorReingreso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ValorReingreso.setText("00.00");
        getContentPane().add(ValorReingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel_reunion3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel_reunion3.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_reunion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_reunion3.setText("Socios");
        getContentPane().add(jLabel_reunion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 570, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombres", "Apellidos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 550, 110));

        jLabel_nombreReunion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_nombreReunion2.setText("Ingrese el código o nombre del usuario a buscar");
        getContentPane().add(jLabel_nombreReunion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 410, 20));

        jButton_guardarAsistencia.setBackground(new java.awt.Color(0, 97, 155));
        jButton_guardarAsistencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_guardarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        jButton_guardarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton_guardarAsistencia.setText("Guardar");
        jButton_guardarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarAsistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 125, 39));

        modificar.setBackground(new java.awt.Color(0, 97, 155));
        modificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/writing (1).png"))); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 150, 39));

        jLabe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabe.setText("Seleccione fecha de pago");
        getContentPane().add(jLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 212, 40));

        fechaCobro.setDateFormatString("yyyy-MM-dd");
        fechaCobro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(fechaCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 128, 340, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setMaximumSize(new java.awt.Dimension(610, 460));
        jLabel2.setMinimumSize(new java.awt.Dimension(610, 460));
        jLabel2.setPreferredSize(new java.awt.Dimension(610, 460));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        jLabel_nombreReunion3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_nombreReunion3.setText("Seleccione el usuario que desea*.");
        getContentPane().add(jLabel_nombreReunion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuarioActionPerformed
        obtenerUsuario();
    }//GEN-LAST:event_jButton_buscarUsuarioActionPerformed

    public void obtenerUsuario() {
        int cont = 0;
        if (fechaCobro.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fecha");
            cont++;
        }
        if (cont == 0) {
            String codigoUsuario = jTextField_codigoUsuario.getText();
            ArrayList<String> usuario = new ArrayList<>();
            if (isNumeric(codigoUsuario)) {
                try {
                    usuario = metodos.obtenerUnicoUsuario(codigoUsuario);
                } catch (SQLException ex) {
                    Logger.getLogger(Reinstalacion1.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    usuario = metodos.obtenerUsuarios(codigoUsuario);
                } catch (SQLException ex) {
                    Logger.getLogger(Reinstalacion1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (!usuario.isEmpty()) {
                DefaultTableModel modelo;
                modelo = new DefaultTableModel();
                modelo.addColumn("Nombre");
                jTable1.setModel(modelo);
                for (int i = 0; i < usuario.size(); i++) {
                    modelo.addRow(new Object[]{usuario.get(i)});
                }

            } else {
                JOptionPane.showMessageDialog(this, "Usuario no registrado");
            }
        }
    }

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    private void jTextField_codigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codigoUsuarioActionPerformed

    private void jButton_guardarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarAsistenciaActionPerformed
        int cont = 0;
        int ano = 0, mes = 0, dia = 0;

        ano = fechaCobro.getCalendar().get(Calendar.YEAR);
        mes = fechaCobro.getCalendar().get(Calendar.MONTH) + 1;
        dia = fechaCobro.getCalendar().get(Calendar.DAY_OF_MONTH);

        String fecha = ano + "-" + mes + "-" + dia;
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        int fila = jTable1.getSelectedRow();
        int id = 0, asistencia = 0;
        double cantidad = 0;
        if (ValorReingreso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            if (isDouble(ValorReingreso.getText())) {
                cantidad = Double.parseDouble(ValorReingreso.getText());
                String nombres, registro;
                // String fecha = (String) jComboBox_reuniones.getSelectedItem();
                manejador mn = new manejador();
                if (fila >= 0) {
                    nombres = String.valueOf(tm.getValueAt(jTable1.getSelectedRow(), 0));
                    try {
                        id = Integer.parseInt(metodos.obtenerID(nombres));
                        metodos.insertarReinstalacion(id, cantidad, fecha);
                        JOptionPane.showMessageDialog(null, "Valor Ingresado Correctamente");
                    } catch (SQLException ex) {
                        Logger.getLogger(Reinstalacion1.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Valor Incorrecto");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor de Reingreso Incorrecto");
            }
        }

    }//GEN-LAST:event_jButton_guardarAsistenciaActionPerformed

    public static boolean isDouble(String cadena) {

        boolean resultado;

        try {
            Double.parseDouble(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        int ano = 0, mes = 0, dia = 0;

        ano = fechaCobro.getCalendar().get(Calendar.YEAR);
        mes = fechaCobro.getCalendar().get(Calendar.MONTH) + 1;
        dia = fechaCobro.getCalendar().get(Calendar.DAY_OF_MONTH);

        String fecha = ano + "-" + mes + "-" + dia;
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        int fila = jTable1.getSelectedRow();
        int id = 0, asistencia = 0;
        double cantidad = 0;
        if (ValorReingreso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            if (isDouble(ValorReingreso.getText())) {
                cantidad = Double.parseDouble(ValorReingreso.getText());
                String nombres, registro;
                // String fecha = (String) jComboBox_reuniones.getSelectedItem();
                manejador mn = new manejador();
                if (fila >= 0) {
                    nombres = String.valueOf(tm.getValueAt(jTable1.getSelectedRow(), 0));

                    try {
                        id = Integer.parseInt(metodos.obtenerID(nombres));
                        metodos.modificarReinstalacion(id, cantidad, fecha);
                        JOptionPane.showMessageDialog(null, "Valor Modificado Correctamente");
                    } catch (SQLException ex) {
                        Logger.getLogger(Reinstalacion1.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Valor Incorrecto");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Costo de Reingreso Incorrecto");
            }
        }
    }//GEN-LAST:event_modificarActionPerformed

    public void obtenerUsuarios() throws SQLException {
        ArrayList<String> usuarios = new ArrayList<>();
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        jTable1.setModel(modelo);
        for (int i = 0; i < usuarios.size() - 1; i = i + 2) {
            modelo.addRow(new Object[]{usuarios.get(i), usuarios.get(i + 1)});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reinstalacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                crearReunion dialog = new crearReunion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ValorReingreso;
    private javax.swing.ButtonGroup buttonGroup_asistencias;
    private com.toedter.calendar.JDateChooser fechaCobro;
    private javax.swing.JButton jButton_buscarUsuario;
    private javax.swing.JButton jButton_guardarAsistencia;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_nombreReunion;
    private javax.swing.JLabel jLabel_nombreReunion2;
    private javax.swing.JLabel jLabel_nombreReunion3;
    private javax.swing.JLabel jLabel_nombreReunion4;
    private javax.swing.JLabel jLabel_reunion3;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_codigoUsuario;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
