/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import aplicativojuntaap.metodos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kami Osita Bebe
 */
public class verReunion extends javax.swing.JDialog {

    public metodos metodos = new metodos();

    /**
     * Creates new form login
     */
    public verReunion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Ver Reuniones");
        this.setResizable(false);
//        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel_titulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_reunion1 = new javax.swing.JLabel();
        jComboBox_reuniones = new javax.swing.JComboBox<String>();
        jLabel_reunion = new javax.swing.JLabel();
        jLabel_reunion2 = new javax.swing.JLabel();
        jTextField_nombreReunion = new javax.swing.JTextField();
        jTextField_descripcionReunion = new javax.swing.JTextField();
        jLabel_reunion3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton_crearReunion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_verAsistencias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_verAtrasos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_verFaltas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1025, 715));
        setPreferredSize(new java.awt.Dimension(1018, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 30)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Ver Reunión");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 980, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 990, 10));

        jLabel_reunion1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_reunion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_reunion1.setText("Seleccione una reunión por su fecha:");
        getContentPane().add(jLabel_reunion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jComboBox_reuniones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_reuniones.setBorder(null);
        jComboBox_reuniones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_reunionesItemStateChanged(evt);
            }
        });
        jComboBox_reuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_reunionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_reuniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 660, -1));

        jLabel_reunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_reunion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_reunion.setText("Nombre Reunión:");
        getContentPane().add(jLabel_reunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 165, 30));

        jLabel_reunion2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_reunion2.setText("Descripción Reunión:");
        getContentPane().add(jLabel_reunion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jTextField_nombreReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_nombreReunion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_nombreReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreReunionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_nombreReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 780, -1));

        jTextField_descripcionReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_descripcionReunion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_descripcionReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descripcionReunionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_descripcionReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 780, -1));

        jLabel_reunion3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel_reunion3.setForeground(new java.awt.Color(28, 108, 171));
        jLabel_reunion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_reunion3.setText("Socios");
        getContentPane().add(jLabel_reunion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 970, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 990, 10));

        jButton_crearReunion.setBackground(new java.awt.Color(0, 97, 155));
        jButton_crearReunion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_crearReunion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_crearReunion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick.png"))); // NOI18N
        jButton_crearReunion.setText("Aceptar");
        jButton_crearReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearReunionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_crearReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 180, 39));

        jTable_verAsistencias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_verAsistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Asiste"
            }
        ));
        jScrollPane3.setViewportView(jTable_verAsistencias);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 312, 336));

        jTable_verAtrasos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_verAtrasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Atraso"
            }
        ));
        jScrollPane2.setViewportView(jTable_verAtrasos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 312, 336));

        jTable_verFaltas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_verFaltas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Falta"
            }
        ));
        jScrollPane4.setViewportView(jTable_verFaltas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 298, 336));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 990, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/texturas-pared-gris-fondo_74190-4389 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_reunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_reunionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_reunionesActionPerformed

    private void jTextField_nombreReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreReunionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreReunionActionPerformed

    private void jTextField_descripcionReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descripcionReunionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descripcionReunionActionPerformed

    private void jComboBox_reunionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_reunionesItemStateChanged
        try {
            obtenerInformacion();
            obtenerRegistrosNombres();
        } catch (SQLException ex) {
            Logger.getLogger(verReunion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox_reunionesItemStateChanged

    private void jButton_crearReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearReunionActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButton_crearReunionActionPerformed

    public void llenarCombo() {
        ArrayList<String> fecha = new ArrayList<>();
        try {
            fecha = metodos.obtenerReuniones();
            for (int i = 0; i < fecha.size(); i++) {
                jComboBox_reuniones.addItem(fecha.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(verReunion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void obtenerInformacion() throws SQLException {
        ArrayList<String> informacion = new ArrayList<>();
        String fecha = (String) jComboBox_reuniones.getSelectedItem();
        informacion = metodos.obtenerInformacionReunion(fecha);
        jTextField_nombreReunion.setText(informacion.get(0));
        jTextField_descripcionReunion.setText(informacion.get(1));
    }

    public void obtenerRegistrosNombres() throws SQLException {
        String fecha = (String) jComboBox_reuniones.getSelectedItem();
        ArrayList<String> asistencias = metodos.obtenerAsiste(fecha);
        ArrayList<String> atrasos = metodos.obtenerAtraso(fecha);
        ArrayList<String> faltas = metodos.obtenerFalta(fecha);
        DefaultTableModel modelo;
        modelo = new DefaultTableModel(){
            public boolean isCellEditable(int filas, int columnas) {
                return false;
            }
        };
        modelo.addColumn("Asistencias");
        jTable_verAsistencias.setModel(modelo);
        for (int i = 0; i < asistencias.size(); i++) {
            modelo.addRow(new Object[]{asistencias.get(i)});
        }
        modelo = new DefaultTableModel() {
            public boolean isCellEditable(int filas, int columnas) {
                return false;
            }
        };

        modelo.addColumn("Atrasos");
        jTable_verAtrasos.setModel(modelo);
        for (int i = 0; i < atrasos.size(); i++) {
            modelo.addRow(new Object[]{atrasos.get(i)});
        }
        modelo = new DefaultTableModel(){
            public boolean isCellEditable(int filas, int columnas) {
                return false;
            }
        };
        modelo.addColumn("Faltas");
        jTable_verFaltas.setModel(modelo);
        for (int i = 0; i < faltas.size(); i++) {
            modelo.addRow(new Object[]{faltas.get(i)});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verReunion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                crearReunion dialog = new crearReunion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_crearReunion;
    private javax.swing.JComboBox<String> jComboBox_reuniones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_reunion;
    private javax.swing.JLabel jLabel_reunion1;
    private javax.swing.JLabel jLabel_reunion2;
    private javax.swing.JLabel jLabel_reunion3;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_verAsistencias;
    private javax.swing.JTable jTable_verAtrasos;
    private javax.swing.JTable jTable_verFaltas;
    private javax.swing.JTextField jTextField_descripcionReunion;
    private javax.swing.JTextField jTextField_nombreReunion;
    // End of variables declaration//GEN-END:variables
}
